### ISSUE TITLE
Error while getting DNS Record info: The session id is not in a valid format.

### ISSUE THREAD

**Issue by CptMyName** [stecklars/dynamic-dns-netcup-api#21]
Hi Lars,
first of all thank you for this great tool!

Over the last few months I've been getting the following error when running the script as a cronjob:

```
Script Starting Oct 04, 2022  21:07.01

Full logs for this script are available at /blabla

[2022/10/04 21:07:01 +0200][NOTICE] =============================================
[2022/10/04 21:07:01 +0200][NOTICE] Running dynamic DNS client for netcup 3.0
[2022/10/04 21:07:01 +0200][NOTICE] This script is not affiliated with netcup.
[2022/10/04 21:07:01 +0200][NOTICE] =============================================

[2022/10/04 21:07:10 +0200][NOTICE] Logged in successfully!
[2022/10/04 21:07:10 +0200][NOTICE] Updating DNS records for domain "cptmynamesdomain.blabla"
[2022/10/04 21:07:15 +0200][NOTICE] Successfully received Domain info.
[2022/10/04 21:07:20 +0200][ERROR] Error while getting DNS Record info: The session id is not in a valid format. Exiting.
Script Finished Oct 04, 2022  21:07.20

Full logs for this script are available at /blabla
```
It has worked without problems before. If I run it manually via console this error only comes up about 50% of the time.

Any idea why this could be happening?
I'm running PHP 7.4.30 and curl 7.85.0 on Unraid 6.11.0. If you need more information feel free to ask!

EDIT: I have been trying around some more and it always seems to be working without errors if I launch the command twice in a row. The first run fails like above and the second one works. I have edited my cronjob to run it every hour at minute 7 and 8 and its working now. Maybe this helps someone...

**Comment by M1scer** [comment]
Hi Lars,

i got the same error message but in my case it seems that it only happens after (at least) one connection retry:

```
[2023/08/31 12:04:03 +0000][NOTICE] =============================================
[2023/08/31 12:04:03 +0000][NOTICE] Running dynamic DNS client for netcup 4.0
[2023/08/31 12:04:03 +0000][NOTICE] This script is not affiliated with netcup.
[2023/08/31 12:04:03 +0000][NOTICE] =============================================

[2023/08/31 12:04:03 +0000][NOTICE] Getting IPv4 address from API.
[2023/08/31 12:04:04 +0000][NOTICE] Logging into netcup CCP DNS API.
[2023/08/31 12:04:08 +0000][NOTICE] Logged in successfully!
[2023/08/31 12:04:08 +0000][NOTICE] Beginning work on domain "domain.de"
[2023/08/31 12:04:08 +0000][NOTICE] Getting Domain info for "domain.de".
[2023/08/31 12:04:38 +0000][WARNING] cURL Error while accessing https://ccp.netcup.net/run/webservice/servers/endpoint.php?JSON: (28) Operation timed out after 30001 milliseconds with 0 bytes received - Retrying in 30 seconds. (Try 1 / 3)
[2023/08/31 12:05:08 +0000][WARNING] Retrying now.
[2023/08/31 12:05:11 +0000][ERROR] Error while getting DNS Zone info: The session id is not in a valid format. Exiting.
```

I have checked a few times and it always fails if it has to retry.

For me it fails more than 50% of the time.

**Comment by stecklars** [comment]
@M1scer At the time you commented this, there was an ongoing issue with the CCP due to incoming DDoS attacks. This should be resolved now, do you still see this issue?

**Comment by titus-kruse** [comment]
Hi Lars,

I still see this issue. Currently multiple times a day. The script runs every 15 minutes. Maybe too often. My IP address at Telekom apparently only changes when I reconnect.

It seems to me that I am the only one with this problem. Is there a better solution since your last update here to set a DNS record with my public IP address?

**Comment by stecklars** [comment]
This is caused by an API level issue (sessions are expiring too early). It is currently being looked into at netcup and depending on how soon a fix will be deployed, as well as my personal time constraints, I may or may not build a workaround.

**Comment by stecklars** [comment]
This should now be fixed in the latest version of the script.

**Comment by OevreFlataeker** [comment]
Still see the error appearing since 2,3 weeks sometimes multiple runs in a row.
